### ISSUE TITLE
Reverse haversine

### ISSUE THREAD

**Issue by shawnngtq** [mapado/haversine#29]
I was wondering if it's possible to implement a reverse haversine function.

Imagine there is a circle, we know the center point (latitude, longitude), and the radius. Return a set of maximum latitude and longitude that a random point can have and still fall within the circle.

I do not understand the math behind this to implement it myself. Happy to help if anyone has the math for it.

**Comment by jdeniau** [comment]
As a matter of fact, there is a PR opened about that : https://github.com/mapado/haversine/pull/19

It is old, so a new implementation might be needed, but it is a good start.

If you are willing to implement it, you can see the code and the comments that may be interesting.
There is a point about implementing a simple geometric approach or a complex approach (because the earth is not flat 😉), feel free to use the approach you like, it will be a good start.

**Comment by jdeniau** [comment]
Fixed by #39
