### ISSUE TITLE
Inverse... compute direction?

### ISSUE THREAD

**Issue by hodgesd** [mapado/haversine#43]
Would it be possible to add a function that computes the direction/bearing from one point to another?  Perhaps even include the option to output cardinal & sub-cardinal directions.

Thank you.

**Comment by jdeniau** [comment]
To be sure that I understand right : you are refering to the `inverse_haversine` method but you want to calculate the radian value between those two points? Did I understood you correctly?

**Comment by hodgesd** [comment]
Given two sets of coordinates A and B, I'd like to calculate the bearing from one to the other.

I was able to accomplish this in Python and am willing to contribute the function to this project... but you'd have to show me how.

**Comment by FriedrichKayak** [comment]
@hodgesd Why did you include the word "inverse" in the title of the issue? I think that's the confusion. By coincidence, just today, I discovered this library and came here to open the same request. I would also consider contributing it to the library, if that's desired.

Example listing:
metropolis = (###, ###)
placeville = (###, ###)
distance = haversine(metropolis, placeville)
bearing = bearing(metropolis, placeville)
cardinal = cardinal(metropolis, placeville)

print("Metropolis is " + str(distance) + " from Placeville on bearing " + str(bearing) + " which is " + cardinal

Example Output:
Metropolis is 145.00000 miles from Placeville on bearing 120.4 which is SOUTH-EAST

**Comment by FriedrichKayak** [comment]
Note: to work with magnetic bearing would require look up tables for magnetic declination/variation.

**Comment by jdeniau** [comment]
@hodgesd @FriedrichKayak any PR is welcome !

You can see the (light) contributing guide [here](https://github.com/mapado/haversine#contributing)

I think that you can create two files:

- haversine/bearing.py
- haversine/cardinal.py

with their test files

- tests/test_bearing.py
- tests/test_cardinal.py

**Comment by PLSeuJ** [comment]
I just stumbled across with a related issue:
I've got location A (lat, lon) and B is x, y meters away from A. What is the lat and lon of B? 
I will open a pull request this week regarding such a change, unless you stop me before.

**Comment by jdeniau** [comment]
@PLSeuJ Oh ! I did see that this is still open. I I read it right, I think that this has been implemented in #39 !

Please reopen if I'm misread this.

**Comment by PLSeuJ** [comment]
@jdeniau it depends. I thought input could be a distance tuple (north distance, east distance) instead of distance and angel. However this of cause depends on the projection type and I don't know if you'd like this to be added to this package or not.
I would make a start with a pull request for the equirectangular projection in case you agree.

**Comment by milancurcic** [comment]
I agree that the "Inverse.." in the title is misleading. But also I don't think this issue should be closed. #39 does not implement a function to return bearing from coordinates.

**Comment by jdeniau** [comment]
@milancurcic I renamed the issue to match the request (I think) and I re-open the issue. Any PR would be welcome here.

@PLSeuJ If I read it right, you have a point, let's say Paris, and you want to go 100 km WEST and 50 km SOUTH for example, instead of calculating the radian for this ?
If I understand correctly, then you could iterate twice with the `inverse_haversine` function :

```py
tmp = inverse_haversine(paris, 100, Direction.WEST)
out = inverse_haversine(tmp, 50, Direction.SOUTH)
```

I don't see a path to include this without a substantial complexification of the API, but if you do we can discuss this in another issue.
